name: Node.js Testing

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      
      - name: Install Mocha
        working-directory: ./functions
        run: npm install --save-dev firebase-functions-test && npm install --save-dev mocha
      
      - name: Create placeholder file
        run: echo "" > ./functions/constants.js


      - name: Mocha Tests
        working-directory: ./functions
        run: npm test

