name: Node.js Testing

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      
      - name: Mocha Tests
        working_directory: ./functions
        run: npm test

